version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: 'heroicons'
      - dependency-name: 'tailwindcss'
      - dependency-name: '@headlessui/*'
    labels:
      - 'dependencies'
